package com.nullpointers.hostandguest;

import com.codename1.io.Log;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.ui.Toolbar;
import com.hostandguest.entities.Message;
import com.hostandguest.entities.User;
import com.hostandguest.views.ChatList;
import com.hostandguest.views.GoogleMapForm;
import com.hostandguest.views.Loginform;
import com.hostandguest.views.addPropertyForm;
import com.hostandguest.views.getAllPropertyForm;
import com.hostandguest.views.getMyPropertyForm;
import java.io.IOException;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class ApplicationLauncher {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }
    
    public void start() {

      Loginform log;
        try {
            log = new Loginform();
            log.showloginform();
        } catch (IOException ex) {
            Log.e(ex);
        }

    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }
    
    public void destroy() {
    }

}
