services:
#    review.example:
#        class: ReviewBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
   review:
       class: ReviewBundle\Controller\ReviewController
       calls:
                   - [ "setContainer", [ "@service_container" ] ]