messaging_home:
    path:     /
    defaults: { _controller: MessagingBundle:Message:inbox }
messaging_homepage:
    path:     /send
    defaults: { _controller: MessagingBundle:Message:sendTo }
messaging_get:
    path:     /get
    defaults: { _controller: MessagingBundle:Message:loadConversation }
messaging_getuserlist:
    path:     /userlist
    defaults: { _controller: MessagingBundle:Message:getUserList }