# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  redirect.login.after:
    class: UserBundle\Redirection\AfterLoginRedirection
    arguments: ["@router"]
  hwi_oauth.user.provider.entity:
    class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider
  my.custom.user_provider:
    class:        UserBundle\Security\Core\User\FOSUBUserProvider
    arguments: ['@fos_user.user_manager', { facebook: facebook_id }]